spring.application.name=inventory-management

spring.datasource.url=jdbc:mysql://localhost:3306/inventory_management

spring.datasource.username=root

spring.datasource.password=Root@123

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=SMBInventorySecretKeyForJWTToken2026MustBeVeryLongSecure
app.jwt.expiration=86400000